// verify_flow_v3.js
// Flowday V3 E2E Database Telemetry Verification Script
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

// Load env variables from .env.local
const envPath = path.resolve('.env.local');
if (!fs.existsSync(envPath)) {
  console.error('❌ .env.local missing');
  process.exit(1);
}
const envFile = fs.readFileSync(envPath, 'utf8');
const urlMatch = envFile.match(/VITE_SUPABASE_URL=(.+)/);
const keyMatch = envFile.match(/VITE_SUPABASE_ANON_KEY=(.+)/);
if (!urlMatch || !keyMatch) {
  console.error('❌ Failed to parse .env.local credentials');
  process.exit(1);
}
const supabase = createClient(urlMatch[1].trim(), keyMatch[1].trim());

async function run() {
  try {
    console.log('🚀 INITIALIZING FLOWDAY V3 E2E TELEMETRY VERIFICATION');
    
    // 1. Login with pre-existing test account
    const testEmail = 'teste@flowday.app';
    const testPassword = 'Password123!';
    const loginRes = await supabase.auth.signInWithPassword({ email: testEmail, password: testPassword });
    if (loginRes.error) throw loginRes.error;
    const userId = loginRes.data.user.id;
    console.log('✅ Logged in successfully. User ID:', userId);

    const tableResults = [];

    // Helper to log event, verify database record and collect metrics
    const logAndVerify = async (type, meta = {}) => {
      console.log(`\n--- Logging and querying event: ${type} ---`);
      
      // Auto-enrich metadata as implemented in V3
      const enrichedMetadata = {
        ...meta,
        platform: 'web',
        device_type: 'desktop',
        screen: '/verify_flow_v3_script',
        app_version: '3.0.0',
        timestamp: new Date().toISOString()
      };

      // Insert
      const { error: insertError } = await supabase.from('events').insert({
        user_id: userId,
        event_type: type,
        metadata: enrichedMetadata
      });
      if (insertError) {
        console.error(`❌ Error inserting event ${type}:`, insertError);
        tableResults.push({ event: type, found: 'Não (Erro de Inserção)', timestamp: 'N/A' });
        return;
      }
      console.log(`✅ Event '${type}' logged successfully.`);

      // Query database directly to confirm and show actual data
      const { data: rec, error: queryError } = await supabase
        .from('events')
        .select('event_type, created_at, user_id, metadata')
        .eq('user_id', userId)
        .eq('event_type', type)
        .order('created_at', { ascending: false })
        .limit(1);

      if (queryError) {
        console.error(`❌ Error querying event ${type}:`, queryError);
        tableResults.push({ event: type, found: 'Não (Erro de Consulta)', timestamp: 'N/A' });
      } else if (rec && rec.length > 0) {
        console.log('🔎 Database Record Found:');
        console.log(`  - event_type: ${rec[0].event_type}`);
        console.log(`  - created_at: ${rec[0].created_at}`);
        console.log(`  - user_id:    ${rec[0].user_id}`);
        console.log(`  - metadata:   ${JSON.stringify(rec[0].metadata)}`);
        tableResults.push({ event: type, found: 'Sim', timestamp: rec[0].created_at });
      } else {
        console.warn(`⚠️ No record found in database for event: ${type}`);
        tableResults.push({ event: type, found: 'Não Encontrado', timestamp: 'N/A' });
      }
    };

    // --- STEP 1: login ---
    await logAndVerify('user_logged_in', { method: 'explicit' });

    // --- STEP 2: onboarding started ---
    await logAndVerify('onboarding_started', { step: 0 });

    // --- STEP 3 & 4: criar meta & concluir meta ---
    const { data: goalData, error: goalError } = await supabase.from('goals')
      .insert({
        user_id: userId,
        title: 'E2E Flowday V3 Goal',
        description: 'Temporary goal generated by E2E script',
        color: '#4A654E',
        icon: '🎯'
      })
      .select();
    if (goalError) throw goalError;
    const goalId = goalData[0].id;
    await logAndVerify('goal_created', { goal_id: goalId, title: 'E2E Flowday V3 Goal' });
    
    // Concluir meta
    const { error: goalUpdateError } = await supabase.from('goals')
      .update({ status: 'completed' })
      .eq('id', goalId);
    if (goalUpdateError) throw goalUpdateError;
    await logAndVerify('goal_completed', { goal_id: goalId });

    // --- STEP 5, 6 & 7: criar tarefa, concluir tarefa, reabrir tarefa ---
    const { data: taskData, error: taskError } = await supabase.from('tasks')
      .insert({
        user_id: userId,
        title: 'E2E Flowday V3 Task',
        description: 'Temporary task generated by E2E script',
        category: 'Trabalho',
        priority: 'Média',
        completed: false
      })
      .select();
    if (taskError) throw taskError;
    const taskId = taskData[0].id;
    await logAndVerify('task_created', { task_id: taskId, title: 'E2E Flowday V3 Task' });

    // Concluir tarefa
    const { error: taskCompleteError } = await supabase.from('tasks')
      .update({ completed: true, completed_at: new Date().toISOString() })
      .eq('id', taskId);
    if (taskCompleteError) throw taskCompleteError;
    await logAndVerify('task_completed', { task_id: taskId });

    // Reabrir tarefa
    const { error: taskReopenError } = await supabase.from('tasks')
      .update({ completed: false, completed_at: null })
      .eq('id', taskId);
    if (taskReopenError) throw taskReopenError;
    await logAndVerify('task_uncompleted', { task_id: taskId });
    await logAndVerify('task_reopened', { task_id: taskId });

    // --- STEP 8: abrir calendário ---
    await logAndVerify('calendar_opened');

    // --- STEP 9 & 10: agendar tarefa & concluir tarefa agendada ---
    const tomorrowStr = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0];
    const { error: taskScheduleError } = await supabase.from('tasks')
      .update({ due_date: tomorrowStr })
      .eq('id', taskId);
    if (taskScheduleError) throw taskScheduleError;
    await logAndVerify('calendar_task_scheduled', { task_id: taskId, date: tomorrowStr });

    // Concluir tarefa agendada
    const { error: taskScheduleCompleteError } = await supabase.from('tasks')
      .update({ completed: true, completed_at: new Date().toISOString() })
      .eq('id', taskId);
    if (taskScheduleCompleteError) throw taskScheduleCompleteError;
    await logAndVerify('calendar_task_completed', { task_id: taskId });

    // --- STEP 11, 12 & 13: abrir planejamento semanal, criar planejamento, concluir planejamento ---
    await logAndVerify('weekly_plan_opened');
    await logAndVerify('weekly_plan_created', { goals_selected: 1 });
    await logAndVerify('weekly_plan_completed', { goals_selected: 1 });

    // --- STEP 14 & 15: iniciar foco & concluir foco ---
    await logAndVerify('focus_session_started', { mode: 'focus', task_id: taskId });
    await logAndVerify('focus_session_completed', { duration_minutes: 25, task_id: taskId });

    // --- STEP 16: logout ---
    await logAndVerify('user_logged_out');

    // Clean up created resources
    console.log('\n🗑️ Cleaning up temporary E2E resources...');
    await supabase.from('tasks').delete().eq('id', taskId);
    await supabase.from('goals').delete().eq('id', goalId);
    console.log('✅ Temporary tasks and goals deleted.');

    // Print final markdown table of results
    console.log('\n--- RESULT TABLE ---');
    console.log('| Evento | Encontrado no banco? | Timestamp |');
    console.log('| ------ | -------------------- | --------- |');
    for (const res of tableResults) {
      console.log(`| ${res.event} | ${res.found} | ${res.timestamp} |`);
    }
    console.log('--------------------\n');

  } catch (err) {
    console.error('❌ Error during flow:', err);
  }
}

run();
