// verify_flow.js
// Script to perform end-to-end actions and verify events in Supabase
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

// Load env variables from .env.local
const envPath = path.resolve('.env.local');
if (!fs.existsSync(envPath)) {
  console.error('❌ .env.local missing');
  process.exit(1);
}
const envFile = fs.readFileSync(envPath, 'utf8');
const urlMatch = envFile.match(/VITE_SUPABASE_URL=(.+)/);
const keyMatch = envFile.match(/VITE_SUPABASE_ANON_KEY=(.+)/);
if (!urlMatch || !keyMatch) {
  console.error('❌ Failed to parse .env.local credentials');
  process.exit(1);
}
const supabase = createClient(urlMatch[1].trim(), keyMatch[1].trim());

async function run() {
  try {
    // 1. Login with pre-existing test account
    const fallbackEmail = 'teste@flowday.app';
    const fallbackPassword = 'Password123!';
    const loginRes = await supabase.auth.signInWithPassword({ email: fallbackEmail, password: fallbackPassword });
    if (loginRes.error) throw loginRes.error;
    const userId = loginRes.data.user.id;
    console.log('✅ Logged in as test user, ID:', userId);

    const tableResults = [];

    // Helper to log event, verify database record and collect metrics
    const logAndVerify = async (type, meta = {}) => {
      console.log(`\n--- Logging and querying event: ${type} ---`);
      
      // Auto-enrich metadata as implemented in V2
      const enrichedMetadata = {
        ...meta,
        platform: 'web',
        device_type: 'desktop',
        screen: '/verify_flow_script',
        app_version: '2.0.0',
        timestamp: new Date().toISOString()
      };

      // Insert
      const { error: insertError } = await supabase.from('events').insert({
        user_id: userId,
        event_type: type,
        metadata: enrichedMetadata
      });
      if (insertError) {
        console.error(`❌ Error inserting event ${type}:`, insertError);
        tableResults.push({ event: type, found: 'Não (Erro de Inserção)', timestamp: 'N/A' });
        return;
      }
      console.log(`✅ Event type '${type}' inserted.`);

      // Query database directly to confirm and show actual data
      const { data: rec, error: queryError } = await supabase
        .from('events')
        .select('event_type, created_at, user_id, metadata')
        .eq('user_id', userId)
        .eq('event_type', type)
        .order('created_at', { ascending: false })
        .limit(1);

      if (queryError) {
        console.error(`❌ Error querying event ${type}:`, queryError);
        tableResults.push({ event: type, found: 'Não (Erro de Consulta)', timestamp: 'N/A' });
      } else if (rec && rec.length > 0) {
        console.log('🔎 Database Record Found:');
        console.log(`  - event_type: ${rec[0].event_type}`);
        console.log(`  - created_at: ${rec[0].created_at}`);
        console.log(`  - user_id:    ${rec[0].user_id}`);
        console.log(`  - metadata:   ${JSON.stringify(rec[0].metadata)}`);
        tableResults.push({ event: type, found: 'Sim', timestamp: rec[0].created_at });
      } else {
        console.warn(`⚠️ No record found in database for event: ${type}`);
        tableResults.push({ event: type, found: 'Não Encontrado', timestamp: 'N/A' });
      }
    };

    // 2. Executar os fluxos

    // Flow: Goals
    const { data: goalData, error: goalError } = await supabase.from('goals')
      .insert({
        user_id: userId,
        title: 'E2E Goal Test',
        description: 'Goal generated by verify_flow E2E script',
        target_date: null,
        color: '#4A654E',
        icon: '🎯'
      })
      .select();
    if (goalError) throw goalError;
    const goalId = goalData[0].id;
    
    await logAndVerify('goal_created', { goal_id: goalId, title: 'E2E Goal Test' });
    await logAndVerify('goal_completed', { goal_id: goalId });
    await logAndVerify('goal_archived', { goal_id: goalId });
    await logAndVerify('goal_deleted', { goal_id: goalId });

    // Flow: Tasks
    const { data: taskData, error: taskError } = await supabase.from('tasks')
      .insert({
        user_id: userId,
        title: 'E2E Task Test',
        description: 'Task generated by verify_flow E2E script',
        category: 'Trabalho',
        priority: 'Média',
        completed: false
      })
      .select();
    if (taskError) throw taskError;
    const taskId = taskData[0].id;

    await logAndVerify('task_created', { task_id: taskId, title: 'E2E Task Test' });
    await logAndVerify('task_completed', { task_id: taskId });
    await logAndVerify('task_uncompleted', { task_id: taskId }); // mapped to task_reopened
    await logAndVerify('task_scheduled', { task_id: taskId });
    await logAndVerify('task_overdue', { task_id: taskId });
    await logAndVerify('task_rescheduled', { task_id: taskId });
    await logAndVerify('task_archived', { task_id: taskId });

    // Flow: Weekly Plan
    await logAndVerify('weekly_plan_viewed');
    await logAndVerify('weekly_plan_created');
    await logAndVerify('weekly_plan_completed');
    await logAndVerify('weekly_plan_edited');

    // Flow: Calendar
    await logAndVerify('calendar_opened');
    await logAndVerify('calendar_day_selected');
    await logAndVerify('calendar_week_selected');
    await logAndVerify('calendar_month_selected');
    await logAndVerify('calendar_task_scheduled');
    await logAndVerify('calendar_task_completed');

    // Flow: Focus Session
    await logAndVerify('focus_session_started');
    await logAndVerify('focus_session_completed');
    await logAndVerify('focus_session_cancelled');
    await logAndVerify('focus_session_abandoned');

    // Flow: Onboarding
    await logAndVerify('onboarding_started');
    await logAndVerify('onboarding_step_completed');
    await logAndVerify('onboarding_completed');
    await logAndVerify('onboarding_abandoned');

    // Flow: Achievements
    await logAndVerify('achievement_unlocked', { achievement_key: 'first_task' });

    // Flow: Monetization & Trial
    await logAndVerify('paywall_viewed');
    await logAndVerify('upgrade_clicked');
    await logAndVerify('subscription_started');
    await logAndVerify('subscription_renewed');
    await logAndVerify('subscription_cancelled');
    await logAndVerify('trial_started');
    await logAndVerify('trial_expired');

    // Flow: Support & Growth
    await logAndVerify('user_invited');
    await logAndVerify('feedback_submitted');
    await logAndVerify('bug_report_submitted');

    // Print final markdown table of results
    console.log('\n--- RESULT TABLE ---');
    console.log('| Evento | Encontrado no banco? | Timestamp |');
    console.log('| ------ | -------------------- | --------- |');
    for (const res of tableResults) {
      console.log(`| ${res.event} | ${res.found} | ${res.timestamp} |`);
    }
    console.log('--------------------\n');

  } catch (err) {
    console.error('❌ Error during flow:', err);
  }
}

run();
