-- ALTERAR A COLUNA TASK_ID PARA ACEITAR VALORES NULOS (Permitindo notificações de Foco/Objetivos)
ALTER TABLE public.notification_queue ALTER COLUMN task_id DROP NOT NULL;

-- GARANTIR QUE A COLUNA STATUS TENHA UM VALOR PADRÃO CASO NÃO SEJA ENVIADO
ALTER TABLE public.notification_queue ALTER COLUMN status SET DEFAULT 'pending';

-- RE-CONCEDER PERMISSÃO PARA O USUÁRIO AUTENTICADO ESCREVER NA FILA VIA TRIGGER
GRANT INSERT, SELECT, UPDATE, DELETE ON public.notification_queue TO authenticated, service_role;